using System.ComponentModel.DataAnnotations;

namespace LawAfrica.API.Models.Payments
{
    /// <summary>
    /// Global-standard invoice header.
    /// InvoiceNumber is always generated server-side and must be unique.
    /// </summary>
    public class Invoice
    {
        public int Id { get; set; }

        // Human-friendly unique invoice number (autogenerated)
        [MaxLength(50)]
        public string InvoiceNumber { get; set; } = string.Empty;

        public InvoiceStatus Status { get; set; } = InvoiceStatus.Issued;

        // Who is billed (optional depending on purpose)
        public int? UserId { get; set; }
        public User? User { get; set; }

        public int? InstitutionId { get; set; }
        public Institution? Institution { get; set; }

        // Why this invoice exists (ties into your business flow)
        public PaymentPurpose Purpose { get; set; }

        // Currency + totals
        [MaxLength(10)]
        public string Currency { get; set; } = "KES";

        public decimal Subtotal { get; set; }
        public decimal TaxTotal { get; set; }
        public decimal DiscountTotal { get; set; }
        public decimal Total { get; set; }

        // Payment tracking (partial payments supported)
        public decimal AmountPaid { get; set; }
        public DateTime? PaidAt { get; set; }

        // ERP/NAV later
        [MaxLength(100)]
        public string? ExternalInvoiceNumber { get; set; }

        [MaxLength(500)]
        public string? Notes { get; set; }

        public DateTime IssuedAt { get; set; } = DateTime.UtcNow;
        public DateTime? DueAt { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime? UpdatedAt { get; set; }
        public string? CustomerName { get; set; }  // ✅ for reconciliation/export


        public List<InvoiceLine> Lines { get; set; } = new();


    }
}
